name: Testing Argocd

on:
  push:
    branches: 
    - main 
    - dev
    - stage
    - prod

permissions:
  contents: read
  
env:
  IMAGE_NAME: naveen
  BRANCH: $(basename ${{ github.ref }})
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        ls -al
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  docker:
        needs: build
        runs-on: ubuntu-latest
        steps:
          -
            name: Checkout
            uses: actions/checkout@v3
            
          - 
            name: Print a message 
            run: echo "${{env.IMAGE_NAME }}"
          -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          -
            name: Login to Docker Hub
            uses: docker/login-action@v2
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
          -
            name: Build and push
            uses: docker/build-push-action@v4
            with:
              context: .
              push: true
              tags: naveenguptaus/${{ env.IMAGE_NAME }}-${{ env.BRANCH }}:${{ github.run_number }}
              
              
              
              
  modifygit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'forritu72/argoinfra'
          token: ${{ secrets.GIT_PASSWORD }}
      - name: modify the image
        run: |
          ls
          git config user.email naveen_gupta_us@hotmail.com
          git config user.name forritu72
          
          
          pwd
          cat myapp/values-$(basename ${{ github.ref }}).yaml
          pwd
         
          sed -Ei "s/(tag:).*/\1 $RUN_NUMBER/" myapp/values-$(basename ${{ github.ref }}).yaml
          cat myapp/values-$(basename ${{ github.ref }}).yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
          RUN_NUMBER: ${{ github.run_number }}
