name: Testing Argocd

on:
  push:
    branches: 
    - main 
    - dev
    - stage
    - prod

permissions:
  contents: read
  
env:
  IMAGE_NAME: $(basename ${{ github.ref }}) 
  BRANCH: $(basename ${{ github.ref }}) 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        ls -al
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    # Storing the value of env.BRANCH into another variable
    - name: Store value in another variable
      id: store-value
      run: |
          echo "::set-output name=ANOTHER_VARIABLE::${{ env.BRANCH }}"
        
    # Now you can use ANOTHER_VARIABLE in other steps or globally as needed.
    - name: Use ANOTHER_VARIABLE in another step
      run: |
          echo "Using ANOTHER_VARIABLE in another step: ${{ steps.store-value.outputs.ANOTHER_VARIABLE }}"
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: naveenguptaus/naveen-${{ env.ANOTHER_VARIABLE }}:${{ github.run_number }}
              
  modifygit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      name: changing the deployment of git repo
      with:
        repository: 'forritu72/argoinfra'
        token: ${{ secrets.GIT_PASSWORD }}
        
    - name: modify the image
      run: |
        ls
        git config user.email naveen_gupta_us@hotmail.com
        git config user.name forritu72
        pwd
        cat myapp/values-${{ github.ref }}.yaml
        pwd
        sed -Ei "s/(tag:).*/\1 $RUN_NUMBER/" myapp/values-${{ github.ref }}.yaml
        cat myapp/values-${{ github.ref }}.yaml
        git add .
        git commit -m "Done by Github Actions Job changemanifest: ${{ github.run_number }}"
        git push origin main
        
      env:
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
        RUN_NUMBER: ${{ github.run_number }}
